### ISSUE TITLE
WARNING Eon: Unexpected error in worker for App Eon

### ISSUE THREAD

**Issue by saria974** [amargo/appdeamon-scripts#12]
Szia Amargo!
Korábban hibátlanulk működött a script, de valamelyik HA frissítés óta nem kapok adatot és az entitások sem jönnek létre.
Megénzéd kérlek, hogy mi/hol lehet a gond?
Alább a logok.
2022-12-15 12:57:22.488517 INFO HASS: Connected to Home Assistant 2022.12.6
2022-12-15 12:58:09.928698 INFO HASS: Evaluating startup conditions
2022-12-15 12:58:10.015031 INFO HASS: Startup condition met: hass state=RUNNING
2022-12-15 12:58:10.016063 INFO HASS: All startup conditions met
2022-12-15 12:58:12.863199 INFO AppDaemon: Got initial state from namespace default
2022-12-15 12:58:14.866896 INFO AppDaemon: Scheduler running in realtime
2022-12-15 12:58:14.870454 INFO AppDaemon: Adding /config/appdaemon/apps to module import path
2022-12-15 12:58:14.871131 INFO AppDaemon: Adding /config/appdaemon/apps/eon to module import path
2022-12-15 12:58:14.871607 INFO AppDaemon: Adding /config/appdaemon/apps/normalized_energy_usage to module import path
2022-12-15 12:58:14.875335 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/hello.py - ignoring
2022-12-15 12:58:14.876321 INFO AppDaemon: Loading App Module: /config/appdaemon/apps/eon/read_eon.py
2022-12-15 12:59:03.590221 INFO AppDaemon: Loading App Module: /config/appdaemon/apps/normalized_energy_usage/normalized_energy_usage.py
2022-12-15 12:59:03.655731 INFO AppDaemon: Initializing app Eon using class Eon from module read_eon
2022-12-15 12:59:03.658171 INFO AppDaemon: Initializing app normalized_energy_usage using class NormalizedEnergyUsage from module normalized_energy_usage
2022-12-15 12:59:03.889453 INFO AppDaemon: App initialization complete
2022-12-15 12:59:04.008670 WARNING Eon: ------------------------------------------------------------
2022-12-15 12:59:04.008987 WARNING Eon: Unexpected error in worker for App Eon:
2022-12-15 12:59:04.009238 WARNING Eon: Worker Ags: {'id': 'b3fe4e65541b49daa547e4492eb34219', 'name': 'Eon', 'objectid': '3a9654cf28994593b00b8f4007d253a8', 'type': 'scheduler', 'function': <bound method Eon.read_data of <read_eon.Eon object at 0x7fad4fc47f70>>, 'pin_app': True, 'pin_thread': 0, 'kwargs': {'interval': 3600, '__thread_id': 'thread-0'}}
2022-12-15 12:59:04.009457 WARNING Eon: ------------------------------------------------------------
2022-12-15 12:59:04.018301 WARNING Eon: Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/appdaemon/threading.py", line 904, in worker
    funcref(self.AD.sched.sanitize_timer_kwargs(app, args["kwargs"]))
  File "/config/appdaemon/apps/eon/read_eon.py", line 50, in read_data
    Config(self.args, self.log)
  File "/config/appdaemon/apps/eon/read_eon.py", line 20, in __init__
    self.__class__.CONFIG['db_user'] = args['db_user']
KeyError: 'db_user'
2022-12-15 12:59:04.018599 WARNING Eon: ------------------------------------------------------------
2022-12-15 12:59:10.159586 WARNING AppDaemon: Excessive time spent in utility loop: 2011.0000000000002ms, 2009.9999999999998ms in check_app_updates(), 1.0000000000004547ms in other
2022-12-15 12:59:13.868664 INFO normalized_energy_usage: Normalizing energy usage
2022-12-15 12:59:20.486254 INFO normalized_energy_usage: START - get_states
2022-12-15 13:00:25.351106 INFO normalized_energy_usage: START - get_states
2022-12-15 13:00:26.240929 INFO normalized_energy_usage: START - get_states
2022-12-15 13:00:26.642103 INFO normalized_energy_usage: START - get_states
2022-12-15 13:00:28.351436 INFO normalized_energy_usage: START - get_states
2022-12-15 13:00:29.314084 INFO normalized_energy_usage: START - get_states
2022-12-15 13:00:29.454366 INFO normalized_energy_usage: START - get_states
2022-12-15 13:00:30.657215 INFO normalized_energy_usage: START - get_states
2022-12-15 13:00:30.982257 WARNING AppDaemon: callback setup() in normalized_energy_usage has now completed
2022-12-15 13:08:27.744350 WARNING AppDaemon: Excessive time spent in utility loop: 13951.0ms, 7.0ms in check_app_updates(), 13944.0ms in other

Köszi előre is!
Üdv:
András

**Comment by amargo** [comment]
Szia András!

Látszólag az a gond, hogy az appdaemon -hoz tartozó yaml fájlból hiányzik a db_user , kérlek nézd meg, ha ott van, akkor másold ide a tartalmát (az érzékeny adatokat kitakarva)

Köszi 😊

ui: folyamatban van az átalakítás, hogy egyértelmű legyen a kód és a config is.

**Comment by saria974** [comment]
Szia Amargo!
Küldöm
Eon:
  module: read_eon
  class: Eon
  eon_url: 'https://energia.eon-hungaria.hu/W1000'
  username: 'xxxxxx@xxxxx.xxxx'
  password: 'xxxxxxxxxx'
  report_id: 'xxxxxxx'
  chart_id: 'xxxxxx'
  last_reset: "2022-07-25T11:25:00+00:00"
  every_hour: 1
  hyphen: 'xxxxxxxxxxxxxxx'
  offset: -2
  host: 192.168.X.Y
  database: xxxxxxxxxx
  username_db: xxxxxxxxxxxx
  password_db: xxxxxxxxxxxx
  1_8_0_sensor: sensor.eon_1_8_0_energy_total
  2_8_0_sensor: sensor.eon_2_8_0_energy_total
  positive_a_energy: sensor.eon_positive_a_energy_power
  negative_a_energy: sensor.eon_negative_a_energy_power
normalized_energy_usage:
  class: NormalizedEnergyUsage
  module: normalized_energy_usage
  host: 192.168.X.Y
  database: xxxxxxxxxxx
  username: xxxxxxxxxxx
  password: xxxxxxxxxxxxx
  offset: -2
  numdays: 4
  every_hour: 1
  1_8_0_sensor: sensor.eon_1_8_0_energy_total
  2_8_0_sensor: sensor.eon_2_8_0_energy_total

**Comment by amargo** [comment]
Az tisztán látszik, hogy nem a main branch-en lévőt használod, hanem ami még fejlesztés alatt van. 

Kérlek használd ezt: https://github.com/amargo/appdeamon-scripts/blob/main/eon/read_eon.py

**Comment by saria974** [comment]
Próbálkoztam, mert az eredetivel sem ment.
Visszraktam, újraindítottam a HA-t, vártam kcisit és most ezzel van tele a log:

2022-12-15 19:21:10.333420 INFO HASS: Connected to Home Assistant 2022.12.6
2022-12-15 19:21:10.336381 WARNING HASS: Error in authentication
2022-12-15 19:21:10.336870 WARNING HASS: Disconnected from Home Assistant, retrying in 5 seconds
2022-12-15 19:21:15.352629 INFO HASS: Connected to Home Assistant 2022.12.6
2022-12-15 19:21:15.356056 WARNING HASS: Error in authentication
2022-12-15 19:21:15.356427 WARNING HASS: Disconnected from Home Assistant, retrying in 5 seconds
2022-12-15 19:21:20.376334 INFO HASS: Connected to Home Assistant 2022.12.6

**Comment by amargo** [comment]
Itt pedig az a gond, hogy az appdaemon nem tud a HA-ba bejelentkezni.

**Comment by saria974** [comment]
Egyelőre nem akar helyreállni a kapcsolat, pedig minden a legfrissebb... lehet az a gond.:).
Különben korábban frankón működött, pár hónapja állt meg értékek kijelzése a fenti hibával.
Szeirntem zárd le, ha sikerül helyreállítanom az appdeamont és HA kapcsolatot, jelentkezem az eredménnyekkel.
Ha nem megy, úgyis kérdezek megint :)
Köszi!

**Comment by amargo** [comment]
Rendben, köszönöm én is :)

**Comment by saria974** [comment]
Leszedtem és újratelepítettem az appdeamont, elindult.
Megint csak megköszönni tudom a munkád és az idődet!
