### ISSUE TITLE
pymysql.err.OperationalError: (1054, "Unknown column 'fixed.created' in 'on clause'")

### ISSUE THREAD

**Issue by csomyy** [amargo/appdeamon-scripts#6]
Miután az eon script elindult és írj az adatokat a rendszerbe, a normalizáló script nem tudja kiolvasni a címbeni hiba miatt.

Itt a teljes log:

2022-06-30 18:19:46.535171 WARNING normalized_energy_usage: ------------------------------------------------------------
2022-06-30 18:19:46.537763 WARNING normalized_energy_usage: Unexpected error in worker for App normalized_energy_usage:
2022-06-30 18:19:46.539743 WARNING normalized_energy_usage: Worker Ags: {'id': '832c21126112407590df992c848c7d60', 'name': 'normalized_energy_usage', 'objectid': '471ef07b340b4c4e849f0ba45f0e2338', 'type': 'scheduler', 'function': <bound method NormalizedEnergyUsage.setup of <normalized_energy_usage.NormalizedEnergyUsage object at 0x749cb1d8>>, 'pin_app': True, 'pin_thread': 1, 'kwargs': {'interval': 54000, '__thread_id': 'thread-1'}}
2022-06-30 18:19:46.542146 WARNING normalized_energy_usage: ------------------------------------------------------------
2022-06-30 18:19:46.555466 WARNING normalized_energy_usage: Traceback (most recent call last):
  File "/config/appdaemon/apps/normalized_energy_usage/normalized_energy_usage.py", line 232, in get_states
    cursor.execute(sql, (eon_type, final_since, final_until))
  File "/usr/lib/python3.10/site-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
  File "/usr/lib/python3.10/site-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "/usr/lib/python3.10/site-packages/pymysql/connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_query_result
    result.read()
  File "/usr/lib/python3.10/site-packages/pymysql/connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "/usr/lib/python3.10/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "/usr/lib/python3.10/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/usr/lib/python3.10/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
**pymysql.err.OperationalError: (1054, "Unknown column 'fixed.created' in 'on clause'")**
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/config/appdaemon/apps/normalized_energy_usage/normalized_energy_usage.py", line 235, in get_states
    self.log(f"ERROR - get_states: {err.message}", level="ERROR")
AttributeError: 'OperationalError' object has no attribute 'message'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/appdaemon/threading.py", line 904, in worker
    funcref(self.AD.sched.sanitize_timer_kwargs(app, args["kwargs"]))
  File "/config/appdaemon/apps/normalized_energy_usage/normalized_energy_usage.py", line 24, in setup
    self.normalize_data(self.args["1_8_0_sensor"], date.date())
  File "/config/appdaemon/apps/normalized_energy_usage/normalized_energy_usage.py", line 151, in normalize_data
    rows = self.get_states(eon_type, date)
  File "/config/appdaemon/apps/normalized_energy_usage/normalized_energy_usage.py", line 238, in get_states
    return rows
UnboundLocalError: local variable 'rows' referenced before assignment
2022-06-30 18:19:46.557998 WARNING normalized_energy_usage: ------------------------------------------------------------

**Comment by amargo** [comment]
Szerintem nem frissítetted azt a scriptet. Tegnap az is változott (elfelejtettem írni) Optimalizálás miatt nincsenek egyben.

**Comment by csomyy** [comment]
A frissítés valóban megoldotta a dolgot, pedig emlékeim szerint frissítettem.
