### ISSUE TITLE
Rossz napi adatok, sensorok eltüntek.

### ISSUE THREAD

**Issue by saria974** [amargo/appdeamon-scripts#9]
Szia @amargo, ismét én :)
A HA tesztrendszeremen (friss HA OS) sikeresen átálltam MariaDB-re, de valamiért nem jó adatokat, illetve folyamatos hibaüzeneteket kapok.
HA
Home Assistant 2022.8.5
Supervisor 2022.08.3
Operating System 8.4
Kezelőfelület 20220802.0 - latest

Elsőre sikerült megkapnom a legutolsó friss adatokat (tegnap éjszakai), majd egy frissítés/újraindítás után a 2 nappal ezelötti adatokat látom a logokban és az érzékelők eltüntek, nincsenek az entítások között.

2022-08-16 13:31:42.030634 INFO Eon: Starting E.ON reader
2022-08-16 13:31:42.038423 INFO normalized_energy_usage: Normalizing energy usage
2022-08-16 13:31:42.073424 INFO normalized_energy_usage: START - get_states
2022-08-16 13:31:42.134266 INFO normalized_energy_usage: sensor.eon_1_8_0_energy_total - 260 set_sum_and_state: 0.0 - 11048.208 - 2022-08-13 21:00
2022-08-16 13:31:42.141923 INFO normalized_energy_usage: START - get_states
2022-08-16 13:31:42.158651 INFO normalized_energy_usage: sensor.eon_2_8_0_energy_total - 284 set_sum_and_state: 0.0 - 7123.741 - 2022-08-13 21:00
2022-08-16 13:31:42.195064 INFO normalized_energy_usage: START - get_states
2022-08-16 13:31:42.224311 INFO normalized_energy_usage: sensor.eon_1_8_0_energy_total - 260 set_sum_and_state: 0.0 - 11048.208 - 2022-08-13 21:00
2022-08-16 13:31:42.239367 INFO normalized_energy_usage: sensor.eon_1_8_0_energy_total - 308 set_sum_and_state: 21.226 - 11069.434 - 2022-08-14 21:00
2022-08-16 13:31:42.262376 INFO normalized_energy_usage: START - get_states
2022-08-16 13:31:42.297003 INFO normalized_energy_usage: sensor.eon_2_8_0_energy_total - 284 set_sum_and_state: 0.0 - 7123.741 - 2022-08-13 21:00
2022-08-16 13:31:42.315601 INFO normalized_energy_usage: sensor.eon_2_8_0_energy_total - 332 set_sum_and_state: 35.084 - 7158.825 - 2022-08-14 21:00
2022-08-16 13:31:42.323924 INFO Eon: get verification token from E.ON portal
2022-08-16 13:31:42.359319 INFO normalized_energy_usage: START - get_states
2022-08-16 13:31:42.380790 INFO normalized_energy_usage: sensor.eon_1_8_0_energy_total - 308 set_sum_and_state: 21.226 - 11069.434 - 2022-08-14 21:00
2022-08-16 13:31:42.388136 INFO normalized_energy_usage: START - get_states
2022-08-16 13:31:42.438535 INFO normalized_energy_usage: sensor.eon_2_8_0_energy_total - 332 set_sum_and_state: 35.084 - 7158.825 - 2022-08-14 21:00
2022-08-16 13:31:42.449597 INFO normalized_energy_usage: START - get_states
2022-08-16 13:31:42.795782 INFO Eon: Start receiving data
2022-08-16 13:31:43.100376 WARNING Eon: ------------------------------------------------------------
2022-08-16 13:31:43.110479 WARNING Eon: Unexpected error in worker for App Eon:
2022-08-16 13:31:43.111836 WARNING Eon: Worker Ags: {'id': '653e7cf6f14a44c5a351d28d4ed6137c', 'name': 'Eon', 'objectid': '7c367b9f10ce4534a82e8fd33972fdf7', 'type': 'scheduler', 'function': <bound method Eon.read_data of <read_eon.Eon object at 0x7f069b461660>>, 'pin_app': True, 'pin_thread': 0, 'kwargs': {'interval': 3600, '__thread_id': 'thread-0'}}
2022-08-16 13:31:43.113173 WARNING Eon: ------------------------------------------------------------
2022-08-16 13:31:43.123580 WARNING Eon: Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/appdaemon/threading.py", line 904, in worker
    funcref(self.AD.sched.sanitize_timer_kwargs(app, args["kwargs"]))
  File "/config/appdaemon/apps/eon/read_eon.py", line 34, in read_data
    self.get_chart_data(profile_data_url, session, eon_1_8_0_report, eon_2_8_0_report)
  File "/config/appdaemon/apps/eon/read_eon.py", line 41, in get_chart_data
    positive_a_energy = self.args['positive_a_energy']
KeyError: 'positive_a_energy'
2022-08-16 13:31:43.126717 WARNING Eon: ------------------------------------------------------------

Küldöm az beállításaimat is:
Eon:
  module: read_eon
  class: Eon
  eon_url: 'https://energia.eon-hungaria.hu/W1000'
  username: 'xxxxx'
  password: 'xxxxxx'
  report_id: 'xxxxx'
  chart_id: 'xxxxx'
  last_reset: "2022-07-25T11:25:00+00:00"
  every_hour: 1
  hyphen: 'xxxxxx'
  offset: -2
  host: 192.168.1.xxx
  database: homeassistant
  username_db: xxxxxx
  password_db: xxxxxx
  1_8_0_sensor: sensor.eon_1_8_0_energy_total
  2_8_0_sensor: sensor.eon_2_8_0_energy_total
normalized_energy_usage:
  class: NormalizedEnergyUsage
  module: normalized_energy_usage
  host: 192.168.1.xxx
  username: xxxxxxx
  password: xxxxxxx
  database: homeassistant
  offset: -2
  numdays: 4
  every_hour: 1
  1_8_0_sensor: sensor.eon_1_8_0_energy_total
  2_8_0_sensor: sensor.eon_2_8_0_energy_total

EON oldal:
![image](https://user-images.githubusercontent.com/58612133/184874467-4af23067-b117-4c11-9ed8-2f7475198a05.png)

Amit látok, hogy valamiért az EON app nem fut le, holott a MariaDB már rendben kellene legyen.
Kérlek pillants rá, hogy mi lehet a gond, mert elég fura ami történik.
Nagyon köszi a segítséget!

**Comment by amargo** [comment]
Hiányos az EON-os config fájl (a minimális leírás hiányos ezzel kapcsolatban, de most gyorsan javítottam).
Ezért írtam korábban, hogy hol van egy közel jó config, de most javítottam kint is:
https://github.com/amargo/appdeamon-scripts/blob/4b0a5ff1288846851b85deaa3a0ed5f404e627bd/README.md?plain=1#L44

Más értékeket is javítottam a leírásban, offset, every_hour.

**Comment by saria974** [comment]
Király vagy, működik!
Annyi kérdés még, hogy ez (is) leszedi 15p a friss adatokat vagy kell még valamit finomítani a beállításokon?

**Comment by amargo** [comment]
Ez leszedi a 15 perces adatokat és megfelelő időbe is rendezi, ezért kell hozzá a MariaDB (csak azt "supportálom").
Az every_hours elég pl 6-8 óránként futnia az offset lehet -3 a hétvége miatt, de kb ennyi :)

**Comment by saria974** [comment]
Szuper vagy, köszi szépen a sgítségedet és a munkádat  :)
